# Generated by Django 3.2.7 on 2021-10-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_filesadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilesAdmin',
        ),
    ]
